### ISSUE TITLE
RFE: Allow validation of Form::Tiny::FieldDefinition `data` attribute

### ISSUE THREAD

**Issue by djerius** [bbrtj/perl-form-tiny#6]
I'd like to catch errors in the user supplied data in a field definition, e.g. in

```
form_field 'field_name' => ( ... { 
    data => { config => { paths => [...] } } 
} );
```
the `data` hash would be validated against something like
```
Dict[ config => 
    Optional[ 
        Dict[ path => Optional[ArrayRef[ NonEmptySimpleStr ] ] ]
    ]
]
```
I don't see a means of doing that, as `Form::Tiny::FieldDefinitionBuilder` explicitly calls `Form::Tiny::FieldDefinition`'s constructor.

One approach would be to add an attribute (e.g. `field_definition_class`) to `Form::Tiny::FieldDefinitionBuilder` which returns the name of the field definition class, and do something similar to `Form::Tiny::Meta` for `Form::Tiny::FieldDefinitionBuilder` (e.g. `form_definition_builder_class`).  That way I could use a plugin to apply a role to `Form::Tiny::Meta` which would change the default value of `form_definition_builder_class` to point at my subclass of `Form::Tiny::FieldDefinitionBuilder` which has an alternate default value for `field_definition_class` which points at a sub-class of `Form::Tiny::FieldDefinition` which adds a type constraint to the `data` attribute.

This sounds really complicated, though.

Alternatively, one could wrap `Form::Tiny::Meta::add_field`, look for the `data` element in the passed parameters, and validate it there.  This is a lot easier, but requires re-implementation of the somewhat complex API of `add_field` to extract the `data` element.

**Comment by bbrtj** [comment]
Hey, 

`Form::Tiny::FieldDefinitionBuilder` is really just an intermediate class that is only needed because of existence of dynamic fields. Its `data` attribute contains everything that will be fed into the constructor of `Form::Tiny::FieldDefinition`, but only if it isn't already blessed into a descendant class of FieldDefinition. What I get from this issue is that you want to specify a `Type::Tiny` type that would be used to validate the format of `data` in `Form::Tiny::FieldDefinition`, not Builder (so only the part documented here: https://metacpan.org/release/BRTASTIC/Form-Tiny-2.13/view/lib/Form/Tiny/FieldDefinition.pm#data)

Can you double-check that current options are not sufficient?
- both static and dynamic fields can use a custom class in place of `Form::Tiny::FieldDefinition` (a descendant). FieldDefinitionBuilder will not modify a constructed object that is a FieldDefinition descendant
- to improve the interface, you can create a plugin that will introduce a DSL keyword calling `->form_meta->add_field` with a constructed object. If the field is dynamic, you can wrap the subroutine to construct the object from the returned hashref dynamically. See https://metacpan.org/release/BRTASTIC/Form-Tiny-2.13/source/lib/Form/Tiny.pm#L93
- your new FieldDefinition descendant can validate `data` however it likes, either add an `isa` to `has '+data'` (if you want to make new classes for each data format) or add a trigger / wrap the writer for more dynamic checking

**Comment by djerius** [comment]
Yes, more abstractly, I would like to use the _existing_ DSL command `form_field`, but with a different FieldDefinition class, and that's not possible.

The argument for this is mainly that implementing the extra flexibility provided by `form_field` in handling different types of  arguments in a new DSL command (e.g. `my_form_field`) requires that I duplicate a large chunk of `form_meta->add_field` in `my_form_field`.

Your suggested approach would bypass the logic in [FieldDefinitionBuilder](https://metacpan.org/release/BRTASTIC/Form-Tiny-2.13/source/lib/Form/Tiny/FieldDefinitionBuilder.pm#L33) which has the possibility that the `Form::Tiny::FieldDefinitionBuilder` is itself returned, rather than a `Form::Tiny::FieldDefinition` object.  Would this be an issue?

**Comment by bbrtj** [comment]
> I would like to use the existing DSL command form_field, but with a different FieldDefinition class, and that's not possible.

This premise is wrong. But just to make sure, I implemented a test which checks it (suprisingly, there wasn't a test for that). It passes with module code unchanged. See https://github.com/bbrtj/perl-form-tiny/blob/master/t/290-custom-field-defs.t#L23

Looks better with `indirect` feature disabled - no parens needed.

> implementing the extra flexibility provided by form_field in handling different types of arguments in a new DSL command (e.g. my_form_field) requires that I duplicate a large chunk of form_meta->add_field in my_form_field.

To some degree, yes. But these are just three possible routes there:
- first argument is not a reference
- first argument is a code reference
- first argument is blessed

If you always want to construct an object of certain class with your parameters, then you just have the first two options to handle. Code reference one:

```
if (ref $first_param eq 'CODE') {
    my $wrapped = $first_param;
    $first_param = sub {
        return MyFieldDef->new($wrapped->(@_));
    };
}
```

And plain argument hash one:

```
if (ref $first_param eq '') {
    $first_param = MyFieldDef->new(
        @other_params,
        name => $first_param
    );
}
```

Then you can pass `$first_param` to `Form::Tiny::Meta->add_field` and everything will just work. Your new DSL keyword will work the same way as `form_field` works, but it will lack the (other) custom objects support.

> Your suggested approach would bypass the logic in [FieldDefinitionBuilder](https://metacpan.org/release/BRTASTIC/Form-Tiny-2.13/source/lib/Form/Tiny/FieldDefinitionBuilder.pm#L33) which has the possibility that the Form::Tiny::FieldDefinitionBuilder is itself returned, rather than a Form::Tiny::FieldDefinition object. Would this be an issue?

This is not an issue. Even if it returns itself, it still holds what it got in its `data` attribute. It's really just a wrapper that is eventually transformed into a FieldDefinition descendant (if it isn't already). You just have to wrap dynamic fields (subroutines) in other subroutines as shown above, since you can't call them during form building.

**Comment by bbrtj** [comment]
Also note: `form_field` with object argument is documented [here](https://metacpan.org/pod/Form::Tiny#form_field)

**Comment by djerius** [comment]
> > I would like to use the existing DSL command form_field, but with a different FieldDefinition class, and that's not possible.
> 
> This premise is wrong. But just to make sure, I implemented a test which checks it (suprisingly, there wasn't a test for that). It passes with module code unchanged. See https://github.com/bbrtj/perl-form-tiny/blob/master/t/290-custom-field-defs.t#L23

My fault; I wasn't precise enough in my statement.  I didn't mean that `form_field` can't handle it, but that there's no means to make `form_field` use an alternative FieldDefinition class internally.  It has to be handed one explicitly.

I've proceeded with the wrapper (as you've laid out), but after implementing it and seeing the resultant Form::Tiny specifications, decided that passing `data` directly to `form_field` exposed too much of the implementation. The user shouldn't need to know that `data` is being used.  So now I've switched to custom DSL keywords which essentially load `data` appropriately, but do the input validation outside of FieldDefinition. 

I'm hoping one day I'll stop rewriting this code! :)

**Comment by bbrtj** [comment]
Seems like you might be more interested in using 'addons' instead of 'data'. They are similar, but main difference is that addons can be built incrementally, which is what you will need for dynamic fields and multiple DSL keyword calls. See https://metacpan.org/pod/Form::Tiny::FieldDefinition#addons

Note: addons are a hash reference which you can't completely hijack, you should choose a single key that will hold your data and only validate that part.

**Comment by bbrtj** [comment]
As for using different field classes: I now understand what you mean, but I think the current interface is good (flexible) enough. The module lets you use a different metaclass implementation for example, through package (our) variable. But I don't like that interface much and if there's another way, I'd avoid it.

**Comment by bbrtj** [comment]
Seems like this one is resolved. @djerius do you still require assistance in this issue, or can it be closed?

**Comment by djerius** [comment]
Hi, sorry for the silence.  I haven't had a chance to review the add-on approach, I'll try that for the next application and see how that fits.

**Comment by bbrtj** [comment]
No problem. Let me know if you need any more assistance, we can always reopen.

Addons aren't well documented, but you can take a look at how `Plugin::Filtered` uses them: https://metacpan.org/release/BRTASTIC/Form-Tiny-2.17/source/lib/Form/Tiny/Plugin/Filtered.pm
