### ISSUE TITLE
Extending a form without adding new fields results in an exception when accessing fields.

### ISSUE THREAD

**Issue by djerius** [bbrtj/perl-form-tiny#8]
`Form::Tiny` version 2.15:

Sample code:

```
use strict;

package ParentForm {
    use Form::Tiny;
    form_field 'inherited_field';
}

package ChildForm {
    use Form::Tiny;
    extends 'ParentForm';
};

ChildForm->new->field_defs;
```
Output:
```
Constructor for ChildForm has been inlined and cannot be updated at [...]/Form/Tiny/Meta.pm line 308.
```

**Comment by djerius** [comment]
The error is emitted by Moo; I'm using Moo version 2.005004

**Comment by bbrtj** [comment]
Hi there!

Thanks for finding this. Form inheritance is not very polished part of this system.

Sadly, this can't easily be fixed without sacrificing something else. Form::Tiny uses metamodel system like Moose, but it does not force a final keyword like `__PACKAGE__->meta->make_immutable;`. Because of this, it does not know when the package is "ready". It just builds its metamodel incrementally when it sees stuff being added to the form. When no stuff is added, there's no place to build the meta. So it only tries to do this when you call `field_defs`, after an object was constructed - which is too late, hence the error.

To fix this, I have to either:
- force a certain syntax construct in this situation. Simple `__PACKAGE__->form_meta;` after `extends 'ParentForm';` fixes this problem, because it forces initialization of the meta before the constructor is first run
- hook in before the constructor to check whether metaobject needs building, possibly sacrificing performance
- hijack the `extends` Moo keyword and force it to also initialize the meta. That may be hard, since it would require faking `caller`

I need some time to choose the right approach. Suggestions?

Edit: The same problem would arise if there was no inheritance at all, just an empty form. This isn't really specific to inheritance, but empty forms make little sense, unlike empty forms which inherit from others.

**Comment by bbrtj** [comment]
I looked into the options I mentioned above. Sadly, none except the first one are possible because Form::Tiny is not tight coupled with any object system. It defaults to Moo, but it can work with anything, even with Object::Pad.

Creating a special DSL for this is an overkill. So as I mentioned previously, the rather ugly `__PACKAGE__->form_meta` before the end of the package is the way to fix the issue. The only way to automate this would be to put `Hooks::AfterRuntime` as a dependency and run `form_meta` method there, but I don't think this kind of hackery is stable enough for a CPAN module.

What was done is:
- if form meta is first built with an object (rather than a package name) an error is raised
- the error much better describes what is happening: `Form ChildForm seems to be empty. Please implement the form or call __PACKAGE__->form_meta explicitly. See Form::Tiny::Manual::Cookbook "Empty forms" section for details`
- Manual::Cookbook now has a section describing this case in detail

Will release to CPAN shortly as 2.16

**Comment by bbrtj** [comment]
2.16 has been released. Thank you for reporting!

**Comment by djerius** [comment]
Sorry for the silence. Thanks for looking at this.
